### ISSUE TITLE
 注册时候提示空指针异常

### ISSUE THREAD

**Issue by baiyz0825** [hongmaple/qq-chat-project#1]
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
at com.baomidou.mybatisplus.core.toolkit.LambdaUtils.resolve(LambdaUtils.java:62) ~[mybatis-plus-core-3.3.2.jar:3.3.2]
	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.columnToString(AbstractLambdaWrapper.java:63) ~[mybatis-plus-core-3.3.2.jar:3.3.2]
	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.columnToString(AbstractLambdaWrapper.java:59) ~[mybatis-plus-core-3.3.2.jar:3.3.2]
	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.columnToString(AbstractLambdaWrapper.java:39) ~[mybatis-plus-core-3.3.2.jar:3.3.2]

**Comment by wwXXXN** [comment]
我也是我都不知道在哪里改 本地测试没没问题 放到服务器上就上面的错误nested exception is org.apache.ibatis.builder.BuilderException: Error evaluating expression 'ew.sqlSegment != null and ew.sqlSegment != '' and ew.nonEmptyOfNormal'. Cause: org.apache.ibatis.ognl.OgnlException: sqlSegment [java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null]

**Comment by wwXXXN** [comment]
兄弟就是jdk版本的问题我是用jdk1.8版本就没问题了

**Comment by baiyz0825** [comment]
我试试
